
### 旧 Verifier（v1 / verifier-api）と新 Verifier2（verifier-api2）の区別

| 比較項目                       | 旧 Verifier（v1 / `verifier-api`）                                                                                                                                                       | 新 Verifier2（`verifier-api2`）                                                                                                                                   |
| :----------------------------- | :--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | :---------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| ステータス                     | 2026年第2四半期（Q2）に非推奨化予定<br>※ 現在はまだ開発チームによるサポートあり                                                                                                          | 現行・アクティブ（Actively Maintained）<br>今後の標準サービス                                                                                                     |
| プロトコルバージョン           | OpenID4VP 草案（Draft 14 / Draft 20）ベース                                                                                                                                              | OpenID4VP 1.0 正式標準（Final Spec）準拠                                                                                                                          |
| クエリ言語<br>要求フォーマット | Presentation Definition（PE / PEX）<br>`input_descriptors` を使用                                                                                                                        | DCQL（Digital Credentials Query Language）<br>`dcql_query` による柔軟な要求が可能                                                                                 |
| 主なコアライブラリ群           | `waltid-openid4vc`<br>`waltid-w3c-credentials`<br>`waltid-verification-policies`                                                                                                         | `waltid-openid4vp`<br>`waltid-dcql`<br>`waltid-digital-credentials`<br>`waltid-verification-policies2`<br>`waltid-vical`                                          |
| デフォルトの公開ポート         | `7003`                                                                                                                                                                                   | `7004`                                                                                                                                                            |
| 新機能・追加ユーティリティ     | 特になし                                                                                                                                                                                 | VICAL（mdoc信頼リスト）の取得・検証機能<br>SSE（Server-Sent Events）および Webhook によるリアルタイム通知                                                         |
| 対応資格情報フォーマット       | `vc+sd-jwt`（IETF SD-JWT VC）<br>※ コード内の不具合を修正する必要あり<br><br>`jwt_vc_json`（W3C VC）<br><br>`mso_mdoc`（ISO モバイル運転免許証）<br>※ コード内の不具合を修正する必要あり | `dc+sd-jwt`（IETF SD-JWT VC）<br>`jwt_vc_json`（W3C VC）<br>`mso_mdoc`（ISO モバイル運転免許証）                                                                  |
| 組み合わせ提示                 | `jwt_vc_json`：複数件の組み合わせ提示が可能<br>`vc+sd-jwt`：1回の提示で指定できるのは1件のみ<br>`mso_mdoc`：1回の提示で指定できるのは1件のみ                                             | 異なる format かつ異なる種類の VC の組み合わせ提示が可能<br><br>例：<br>`jwt_vc_json` + `jwt_vc_json`<br>`jwt_vc_json` + `dc+sd-jwt`<br>`dc+sd-jwt` + `dc+sd-jwt` |

- 参考文献
  - [waltid-verifier-api2/README.md](https://github.com/walt-id/waltid-identity/blob/v0.21.0/waltid-services/waltid-verifier-api2/README.md)
  - [waltid-verifier-api/README.md](https://github.com/walt-id/waltid-identity/blob/v0.21.0/waltid-services/waltid-verifier-api/README.md)
