| 試験番号     | 区分          | 大項目      | 中項目                        | 小項目                                     | 試験内容                                                            | 期待結果                                                                                                                                                     |
| ------------ | ------------- | ----------- | ----------------------------- | ------------------------------------------ | ------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| ccs-6612-101 | Verifier 追加 |             | ログイン                      | 組織ユーザでのログイン                     | 組織ユーザで verifier-web にログインする                            | ログインでき、画面が正常に表示されること                                                                                                                     |
| ccs-6612-102 | Verifier 追加 |             | ログイン                      | 個人ユーザでのログイン                     | 個人ユーザで verifier-web にログインする                            | ログインでき、画面が正常に表示されること                                                                                                                     |
| ccs-6612-101 | Verifier 追加 |             | ログイン                      | 存在しない組織ユーザでのログイン           | 存在しない組織ユーザで verifier-web へのログインを試行する          | ログインできないこと                                                                                                                                         |
| ccs-6612-102 | Verifier 追加 |             | ログイン                      | 存在しない個人ユーザでのログイン           | 存在しない個人ユーザで verifier-web へのログインを試行する          | ログインできないこと                                                                                                                                         |
| ccs-6612-103 | Verifier 追加 |             | Presentation request 発行     | 組織ユーザによる Presentation request 発行 | 組織ユーザで発行画面から Presentation request を発行する            | Presentation request が正常に発行され、Presentation request URL 一覧に発行された Presentation request URL が表示されること                                   |
| ccs-6612-104 | Verifier 追加 |             | Presentation request 発行     | 個人ユーザによる Presentation request 発行 | 個人ユーザで発行画面から Presentation request を発行する            | Presentation request が正常に発行され、Presentation request URL 一覧に発行された Presentation request URL が表示されること                                   |
| ccs-6612-105 | Verifier 追加 |             | Presentation request URL 表示 | 組織ユーザによる Presentation request 表示 | 組織ユーザでログインし、Presentation request URL 一覧画面を表示する | 設定ファイルに設定されたグループ ID に属する Presentation request URL がすべて表示され、他のグループ ID に属する Presentation request URL は表示されないこと |
| ccs-6612-105 | Verifier 追加 |             | Presentation request URL 表示 | 個人ユーザによる Presentation request 表示 | 個人ユーザでログインし、Presentation request URL 一覧画面を表示する | 自身に発行された Presentation request URL のみ表示されること                                                                                                 |
| ccs-6612-107 | Verifier 追加 |             | wallet-web 提示               | 証明書提示確認                             | wallet-web で証明書提示処理を行う                                   | 提示可能な証明書一覧に、自身に発行された Presentation request URL に紐づく証明書のみ表示されること                                                           |
| ccs-6612-112 | Verifier 追加 | VC 提示     | 既存 Verifier                 | JWT 形式 VC 提示                           | 新規 Verifier で発行した JWT 形式 VC を既存 Verifier に提示する     | 提示結果が正常（OK）で、情報が期待どおりに表示されること                                                                                                     |
| ccs-6612-113 | Verifier 追加 | VC 提示     | 既存 Verifier                 | SD-JWT 形式 VC 提示                        | 新規 Verifier で発行した SD-JWT 形式 VC を既存 Verifier に提示する  | 提示結果が正常（OK）で、内容が期待どおりに表示されること                                                                                                     |
| ccs-6612-114 | Verifier 追加 | VC 提示     | 新規 Verifier                 | JWT 形式 VC 提示                           | 新規 Verifier で発行した JWT 形式 VC を新規 Verifier に提示する     | 提示結果が正常（OK）で、情報が期待どおりに表示されること                                                                                                     |
| ccs-6612-115 | Verifier 追加 | VC 提示     | 新規 Verifier                 | SD-JWT 形式 VC 提示                        | 新規 Verifier で発行した SD-JWT 形式 VC を新規 Verifier に提示する  | 提示結果が正常（OK）で、内容が期待どおりに表示されること                                                                                                     |
| ccs-6612-117 | Verifier 追加 | VC 失効     | 既存 Verifier                 | 失効 VC 提示                               | 失効された VC を既存 Verifier に提示し、検証する                    | 証明書状態の検証結果が NG となること                                                                                                                         |
| ccs-6612-117 | Verifier 追加 | VC 失効     | 新規 Verifier                 | 失効 VC 提示                               | 失効された VC を新規 Verifier に提示し、検証する                    | 証明書状態の検証結果が NG となること                                                                                                                         |
| ccs-6612-118 | Verifier 追加 |             | DB 接続異常                   | DB 停止時の動作                            | DB を停止し、Presentation request URL 一覧画面を開く                | Presentation request 一覧を取得できず、エラーが表示されること                                                                                                 |
| ccs-6612-119 | Verifier 追加 |             | waltid verifier-api 接続異常  | 停止時の Presentation request 発行         | waltid verifier-api を停止し、Presentation request 発行処理を実行する | Presentation request の発行ができず、エラーが返却されること                                                                                                   |
| ccs-6612-120 | Verifier 追加 |             | Keycloak 接続異常             | ログイン                                   | Keycloak を停止し、verifier-web へアクセスする                      | verifier-web にログインできず、エラー表示が行われること                                                                                                       |
| ccs-6612-121 | Verifier 追加 |             | verifier-api 接続異常         | API 停止時の動作                           | verifier-api を停止し、Presentation request URL 一覧画面を開く      | Presentation request 一覧を取得できず、エラーが表示されること                                                                                                 |

